### ISSUE TITLE
RocketMQ源码分析Message顺序发送与消费中的问题

### ISSUE THREAD

**Issue by carryxyh** [YunaiV/Blog#3]
在`移除消息队列`章节中，对`removeUnnecessaryMessageQueue`方法的解释中，第一段解释中写到：

> 获取消息队列消费锁，避免和消息队列消费冲突。如果获取锁失败，则移除消息队列失败，等待下次重新分配消费队列时，再进行移除。如果未获得锁而进行移除，则可能出现另外的 Consumer 和当前 Consumer 同时消费该消息队列，导致消息无法严格顺序消费。

我觉得错误的地方出现在`如果未获得锁而进行移除，则可能出现另外的 Consumer 和当前 Consumer 同时消费该消息队列`这里，其实是不会出现另外的Consumer和当前Consumer同事消费消息队列的情况的，因为ProcessQueue是本地队列，ProcessQueue的锁也是本地锁。

这里锁住的原因是在`ConsumeMessageOrderlyService`的`ConsumeRequest`中，其中有这样一段代码：

> this.processQueue.getLockConsume().lock();
> if (this.processQueue.isDropped()) {
>     log.warn("consumeMessage, the message queue not be able to consume, because it's dropped. {}",
>         this.messageQueue);
>     break;
> }
> status = messageListener.consumeMessage(Collections.unmodifiableList(msgs), context);

也就是说，顺序消费时，processQueue是先上锁后消费的，主要是防止多个线程消费同一个ProcessQueue，而不是防止多个Consumer。

说回`removeUnnecessaryMessageQueue`中获取锁的原因的解释部分应该改成如下：

**如果未获得锁而进行移除，则可能导致移除正在消费中的队列**

**Comment by YunaiV** [comment]
@carryxyh 谢谢指出。

T T 都不造都有胖友发 issue 。感谢 1024

**Comment by carryxyh** [comment]
没事没事，谢谢芋艿大大的文章，带我入门~
