### ISSUE TITLE
看了一半天 干货都要加知识星球付费99才能看

### ISSUE THREAD

**Issue by stackvoid** [YunaiV/Blog#5]
。。。。。。

**Comment by youbooks** [comment]
我也遇到跟你一样的情况，他妈的，这个芋道源码 傻逼作者 搞了很大的噱头，他妈的都是先收钱 才能看，百分百九十都是他网上找的开源框架 源码分析的文章 这个傻逼作者收藏后， 估计进群里面看的也是这些

**Comment by JonXia** [comment]
没错，钱白花了，所谓的知识付费坑真的多

**Comment by Coneboy-k** [comment]
@youbooks  不黑不吹。
我个人认为收费没啥。有些原创资源收费没啥。付费才有激起其他人原创写作的兴趣。的确有些知识付费的确比较坑。但我觉得芋道的作者有些资源还不错。从他整合资源，并且二次加工角度来看，你其实已经省下时间了，这就是价值。

---
ps ：另外举一个不恰当的例子， 一个妓女，穿的特别风骚，你看了立马就来了性趣，想来过ppp，对不起，先把费付了。

**Comment by YunaiV** [comment]
@youbooks you

建议做下客观评价。

iocoder.cn 我自己写了大概 200 多篇源码解析放出来。涉及 spring-cloud-gateway、apollo、skywalking、sharding-jdbc、mycat、eureka、hystrix、elastic-job-lite、elastic-job-cloud、部分 rxjava 。这些都是开放的。

因为个人精力的问题，所以会有很多人希望有别的源码解析，所以我就去整理。可能你没做过这个事情，不知道整理文章需要花多少时间。而且，很多整理的文章，不仅仅是简单的整理，我都重新去看，去处理掉一些可能没写清楚的地方。

每个人的时间都是非常宝贵的，大家互相理解。

每个人都会长大，会有妻子，会有孩子。写这些东西，是会失去陪伴她们的时间。所以，我自己是非常理解，为什么每本书的前面，会感谢家庭。对于我，还是要考虑家庭责任感。

中间也有出版社、极客时间、掘金来邀请写书或者专栏，都拒绝了。因为考虑这种形式不好做源码的解惑和交流，所以没答应。

@Coneboy-k 感谢理解。

**Comment by YunaiV** [comment]
@stackvoid 开放的也很多是干货。

明年（2019）可能会写 JVM 发在 iocoder.cn 。具体没定。看精力。
